project 'Smack.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Smack' do

  # Pods for Smack
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift', '~> 1.1'


end
